name: Test

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Environment
        default: 'integration'
        options:
        - integration
        - stg
        - prd
      environment:
        description: 'Environment to run tests against'
        type: environment
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.inputs.choice == 'stg'
        run: echo ${{ github.event.inputs.choice }} Hello
      - name: Run test
        env:
          GITHUB_TOKEN: ${{ secrets.CI_KARGO_TOKEN }}
        run: |
          echo ${{ github.event.inputs.choice }}
          echo $GITHUB_TOKEN
          echo ${{ secrets.CI_KARGO_TOKEN }}
